"""GR00T data config definitions.

Each entry maps a config name to its field values. "_extends" starts from
the parent's values, then overrides the specified keys.
"""

_DATA_CONFIG_DEFS = {
    # SO-100
    "so100": {
        "video_keys": ["video.webcam"],
        "state_keys": ["state.single_arm", "state.gripper"],
        "action_keys": ["action.single_arm", "action.gripper"],
        "language_keys": ["annotation.human.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "so100_dualcam": {
        "_extends": "so100",
        "video_keys": ["video.front", "video.wrist"],
    },
    "so100_4cam": {
        "_extends": "so100",
        "video_keys": ["video.front", "video.wrist", "video.top", "video.side"],
    },
    # SO-101
    "so101": {
        "video_keys": ["video.webcam"],
        "state_keys": ["state.single_arm", "state.gripper"],
        "action_keys": ["action.single_arm", "action.gripper"],
        "language_keys": ["annotation.human.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "so101_dualcam": {
        "_extends": "so101",
        "video_keys": ["video.front", "video.wrist"],
    },
    "so101_tricam": {
        "_extends": "so101",
        "video_keys": ["video.front", "video.wrist", "video.side"],
    },
    # Fourier GR-1
    "fourier_gr1_arms_only": {
        "video_keys": ["video.ego_view"],
        "state_keys": ["state.left_arm", "state.right_arm", "state.left_hand", "state.right_hand"],
        "action_keys": ["action.left_arm", "action.right_arm", "action.left_hand", "action.right_hand"],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "fourier_gr1_arms_waist": {
        "_extends": "fourier_gr1_arms_only",
        "state_keys": [
            "state.left_arm",
            "state.right_arm",
            "state.left_hand",
            "state.right_hand",
            "state.waist",
        ],
        "action_keys": [
            "action.left_arm",
            "action.right_arm",
            "action.left_hand",
            "action.right_hand",
            "action.waist",
        ],
        "language_keys": ["annotation.human.coarse_action"],
    },
    "fourier_gr1_full_upper_body": {
        "_extends": "fourier_gr1_arms_only",
        "video_keys": ["video.front_view"],
        "state_keys": [
            "state.left_arm",
            "state.right_arm",
            "state.left_hand",
            "state.right_hand",
            "state.waist",
            "state.neck",
        ],
        "action_keys": [
            "action.left_arm",
            "action.right_arm",
            "action.left_hand",
            "action.right_hand",
            "action.waist",
            "action.neck",
        ],
    },
    # Unitree G1
    "unitree_g1": {
        "video_keys": ["video.ego_view"],
        "state_keys": ["state.left_arm", "state.right_arm", "state.left_hand", "state.right_hand"],
        "action_keys": ["action.left_arm", "action.right_arm", "action.left_hand", "action.right_hand"],
        "language_keys": ["annotation.human.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "unitree_g1_full_body": {
        "_extends": "unitree_g1",
        "video_keys": ["video.ego_view"],
        "state_keys": [
            "state.left_leg",
            "state.right_leg",
            "state.waist",
            "state.left_arm",
            "state.right_arm",
            "state.left_hand",
            "state.right_hand",
        ],
        "action_keys": [
            "action.left_leg",
            "action.right_leg",
            "action.waist",
            "action.left_arm",
            "action.right_arm",
            "action.left_hand",
            "action.right_hand",
        ],
    },
    "unitree_g1_locomanip": {
        # Mirrors upstream Isaac-GR00T N1.6 "unitree_g1"
        "_extends": "unitree_g1",
        "video_keys": ["video.ego_view"],
        "state_keys": [
            "state.left_leg",
            "state.right_leg",
            "state.waist",
            "state.left_arm",
            "state.right_arm",
            "state.left_hand",
            "state.right_hand",
        ],
        "action_keys": [
            "action.left_arm",
            "action.right_arm",
            "action.left_hand",
            "action.right_hand",
            "action.waist",
            "action.base_height_command",
            "action.navigate_command",
        ],
        "language_keys": ["annotation.human.task_description"],
        "action_indices": list(range(30)),
    },
    # Franka Panda
    "bimanual_panda_gripper": {
        "video_keys": ["video.right_wrist_view", "video.left_wrist_view", "video.front_view"],
        "state_keys": [
            "state.right_arm_eef_pos",
            "state.right_arm_eef_quat",
            "state.right_gripper_qpos",
            "state.left_arm_eef_pos",
            "state.left_arm_eef_quat",
            "state.left_gripper_qpos",
        ],
        "action_keys": [
            "action.right_arm_eef_pos",
            "action.right_arm_eef_rot",
            "action.right_gripper_close",
            "action.left_arm_eef_pos",
            "action.left_arm_eef_rot",
            "action.left_gripper_close",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "bimanual_panda_hand": {
        "video_keys": ["video.right_wrist_view", "video.left_wrist_view", "video.ego_view"],
        "state_keys": [
            "state.right_arm_eef_pos",
            "state.right_arm_eef_quat",
            "state.right_hand",
            "state.left_arm_eef_pos",
            "state.left_arm_eef_quat",
            "state.left_hand",
        ],
        "action_keys": [
            "action.right_arm_eef_pos",
            "action.right_arm_eef_rot",
            "action.right_hand",
            "action.left_arm_eef_pos",
            "action.left_arm_eef_rot",
            "action.left_hand",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "single_panda_gripper": {
        "video_keys": ["video.left_view", "video.right_view", "video.wrist_view"],
        "state_keys": [
            "state.end_effector_position_relative",
            "state.end_effector_rotation_relative",
            "state.gripper_qpos",
            "state.base_position",
            "state.base_rotation",
        ],
        "action_keys": [
            "action.end_effector_position",
            "action.end_effector_rotation",
            "action.gripper_close",
            "action.base_motion",
            "action.control_mode",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    # OXE — mirrors upstream Isaac-GR00T N1.6
    "oxe_droid": {
        "video_keys": ["video.exterior_image_1_left", "video.wrist_image_left"],
        "state_keys": ["state.joint_position", "state.gripper_position"],
        "action_keys": ["action.joint_position", "action.gripper_position"],
        "language_keys": ["annotation.language.language_instruction"],
        "observation_indices": [0],
        "action_indices": list(range(32)),
    },
    "oxe_google": {
        "video_keys": ["video.image"],
        "state_keys": [
            "state.x",
            "state.y",
            "state.z",
            "state.rx",
            "state.ry",
            "state.rz",
            "state.rw",
            "state.gripper",
        ],
        "action_keys": [
            "action.x",
            "action.y",
            "action.z",
            "action.roll",
            "action.pitch",
            "action.yaw",
            "action.gripper",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(8)),
    },
    "oxe_widowx": {
        "video_keys": ["video.image_0"],
        "state_keys": [
            "state.x",
            "state.y",
            "state.z",
            "state.roll",
            "state.pitch",
            "state.yaw",
            "state.pad",
            "state.gripper",
        ],
        "action_keys": [
            "action.x",
            "action.y",
            "action.z",
            "action.roll",
            "action.pitch",
            "action.yaw",
            "action.gripper",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(8)),
    },
    # Simulation
    "libero_panda": {
        "video_keys": ["video.image", "video.wrist_image"],
        "state_keys": [
            "state.x",
            "state.y",
            "state.z",
            "state.roll",
            "state.pitch",
            "state.yaw",
            "state.gripper",
        ],
        "action_keys": [
            "action.x",
            "action.y",
            "action.z",
            "action.roll",
            "action.pitch",
            "action.yaw",
            "action.gripper",
        ],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    # AgiBot
    "agibot_genie1": {
        "video_keys": ["video.top_head", "video.hand_left", "video.hand_right"],
        "state_keys": [
            "state.left_arm_joint_position",
            "state.right_arm_joint_position",
            "state.left_effector_position",
            "state.right_effector_position",
            "state.head_position",
            "state.waist_position",
        ],
        "action_keys": [
            "action.left_arm_joint_position",
            "action.right_arm_joint_position",
            "action.left_effector_position",
            "action.right_effector_position",
            "action.head_position",
            "action.waist_position",
            "action.robot_velocity",
        ],
        "language_keys": ["annotation.language.action_text"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
    "agibot_dual_arm_gripper": {
        "video_keys": ["video.head", "video.left_hand", "video.right_hand"],
        "state_keys": ["state.left_arm", "state.right_arm", "state.left_gripper", "state.right_gripper"],
        "action_keys": ["action.left_arm", "action.right_arm", "action.left_gripper", "action.right_gripper"],
        "language_keys": ["annotation.language.action_text"],
        "observation_indices": [0],
        "action_indices": list(range(30)),
    },
    "agibot_dual_arm_dexhand": {
        "video_keys": ["video.head", "video.left_hand", "video.right_hand"],
        "state_keys": ["state.left_arm", "state.right_arm", "state.left_hand", "state.right_hand"],
        "action_keys": ["action.left_arm", "action.right_arm", "action.left_hand", "action.right_hand"],
        "language_keys": ["annotation.language.action_text"],
        "observation_indices": [0],
        "action_indices": list(range(30)),
    },
    "agibot_dual_arm_full": {
        "video_keys": ["video.head", "video.left_hand", "video.right_hand"],
        "state_keys": [
            "state.left_arm",
            "state.right_arm",
            "state.left_gripper",
            "state.right_gripper",
            "state.head",
            "state.waist",
        ],
        "action_keys": [
            "action.left_arm",
            "action.right_arm",
            "action.left_gripper",
            "action.right_gripper",
            "action.head",
            "action.waist",
            "action.base_velocity",
        ],
        "language_keys": ["annotation.language.action_text"],
        "observation_indices": [0],
        "action_indices": list(range(30)),
    },
    # Galaxea
    "galaxea_r1_pro": {
        "video_keys": ["video.head_camera_rgb"],
        "state_keys": ["state.left_arm", "state.right_arm", "state.left_hand", "state.right_hand"],
        "action_keys": ["action.left_arm", "action.right_arm", "action.left_hand", "action.right_hand"],
        "language_keys": ["annotation.human.action.task_description"],
        "observation_indices": [0],
        "action_indices": list(range(16)),
    },
}

_ALIASES = {
    "agibot_dual_arm": "agibot_dual_arm_gripper",
}
